name: Release Builder

on:
  push:
   branches: [ main, master ]
   tags: 
      - 'v*'
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Web Application
        run: npm run build

      - name: Build exe Application
        run: npm run desktop:pack 
      - name: Upload Binaries and Certificate Artifacts
        if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v5
        with:
           name: ani-gui-${{ matrix.target }}-Release
           path: |
             electron/*
           if-no-files-found: error
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8.0.2  
        with:
           path: downloaded_artifacts
      - name: Determine Tag Name for Release
        id: get_tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
          # Fallback for manual workflow_dispatch runs
             echo "TAG_NAME=v1.3.0-build-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          fi
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          generate_release_notes: true
          draft: false
          prerelease: false
      
          
      
       
